spring.application.name=CollegeCRUD
spring.datasource.url=Jdbc:mysql://root:JlXURtFKHBHcMCuxaqiNRQwXVkeLOfsV@nozomi.proxy.rlwy.net:23751/railway
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update